//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SupportStudentSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CT_Diem_HK
    {
        public string MaHK { get; set; }
        public string MSSV { get; set; }
        public string MaMH { get; set; }
        public string Diem1 { get; set; }
        public string Diem2 { get; set; }
        public string Diem3 { get; set; }
        public string DiemHe10 { get; set; }
        public string DiemChu { get; set; }
        public string DiemHe4 { get; set; }
    }
}
