//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SupportStudentSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CT_HK
    {
        public string MaHK { get; set; }
        public string MSSV { get; set; }
        public Nullable<int> TongTC { get; set; }
        public Nullable<int> SoTC_Dat { get; set; }
        public Nullable<int> SoTC_TichLuy { get; set; }
        public Nullable<double> DiemTB_HK_He10 { get; set; }
        public Nullable<double> DiemTB_HK_He4 { get; set; }
        public Nullable<double> DiemTL_He10 { get; set; }
        public Nullable<double> DiemTL_He4 { get; set; }
    }
}
