//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SupportStudentSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CT_LichThi
    {
        public long STT { get; set; }
        public string MSSV { get; set; }
        public string HoLot { get; set; }
        public string Ten { get; set; }
        public string MaMH { get; set; }
        public string TenMH { get; set; }
        public string NhomThi { get; set; }
        public string ToThi { get; set; }
        public System.DateTime NgayThi { get; set; }
        public string GioThi { get; set; }
        public string PhongThi { get; set; }
    }
}
