//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SupportStudentSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DiemQuyDoi
    {
        public string DiemChu { get; set; }
        public Nullable<double> DiemMin { get; set; }
        public Nullable<double> DiemMax { get; set; }
        public Nullable<double> DiemHe4 { get; set; }
    }
}
