//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SupportStudentSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DonDeNghiXetTotNghiep
    {
        public string DonTuID { get; set; }
        public string CCTAID { get; set; }
        public string SoHieu_CCTA { get; set; }
        public string SoVaoSo_CCTA { get; set; }
        public Nullable<System.DateTime> NgayCap_CCTA { get; set; }
        public string CCTHID { get; set; }
        public string SoHieu_CCTH { get; set; }
        public string SoVaoSo_CCTH { get; set; }
        public Nullable<System.DateTime> NgayCap_CCTH { get; set; }
        public string CCNHID1 { get; set; }
        public string SoHieu_CCNH1 { get; set; }
        public string SoVaoSo_CCNH1 { get; set; }
        public Nullable<System.DateTime> NgayCap_CCNH1 { get; set; }
        public string CCNHID2 { get; set; }
        public string SoHieu_CCNH2 { get; set; }
        public string SoVaoSo_CCNH2 { get; set; }
        public Nullable<System.DateTime> NgayCap_CCNH2 { get; set; }
    }
}
