//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SupportStudentSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DonTu
    {
        public string DonTuID { get; set; }
        public Nullable<System.DateTime> NgayNopDon { get; set; }
        public string LoaiDonTuID { get; set; }
        public string MSSV { get; set; }
        public string NguoiXuLy { get; set; }
        public string KHXuLy { get; set; }
        public string TinhTrang { get; set; }
        public Nullable<bool> TrangThai { get; set; }
        public string GhiChu { get; set; }
    }
}
