//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SupportStudentSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DonXinNhanDiemI_HoanThi
    {
        public string DonTuID { get; set; }
        public string HocPhanID { get; set; }
        public string LyDo { get; set; }
        public string MinhChung { get; set; }
    }
}
