//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SupportStudentSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DonXinChuyenCaThi
    {
        public string DonTuID { get; set; }
        public string MaMH_Cu { get; set; }
        public string NhomThi_Cu { get; set; }
        public string ToThi_Cu { get; set; }
        public string PhongThi_Cu { get; set; }
        public Nullable<System.DateTime> NgayThi_Cu { get; set; }
        public string GioThi_Cu { get; set; }
        public string MaMH_Moi { get; set; }
        public string NhomThi_Moi { get; set; }
        public string ToThi_Moi { get; set; }
        public string PhongThi_Moi { get; set; }
        public Nullable<System.DateTime> NgayThi_Moi { get; set; }
        public string GioThi_Moi { get; set; }
        public string LyDo { get; set; }
        public string MinhChung { get; set; }
    }
}
