//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SupportStudentSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DonXinThiXoaDiemI
    {
        public string DonTuID { get; set; }
        public string DonXinNhanDiemI_ID { get; set; }
        public string HocPhanID { get; set; }
        public string NhomThi { get; set; }
        public string ToThi { get; set; }
        public Nullable<System.DateTime> NgayThi { get; set; }
        public string PhongThi { get; set; }
        public string GioThi { get; set; }
    }
}
