//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SupportStudentSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LichThi
    {
        public int STT { get; set; }
        public string LopSV { get; set; }
        public string MaMH { get; set; }
        public string TenMH { get; set; }
        public Nullable<byte> SoTC { get; set; }
        public string NhomThi { get; set; }
        public string ToThi { get; set; }
        public Nullable<byte> SoLuongThi { get; set; }
        public string HinhThucThi { get; set; }
        public Nullable<byte> SoPhutThi { get; set; }
        public Nullable<byte> Thu { get; set; }
        public Nullable<System.DateTime> Ngay { get; set; }
        public string Gio { get; set; }
        public string Phong { get; set; }
        public string DVQL_SV { get; set; }
        public string DVQL_MH { get; set; }
    }
}
