//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SupportStudentSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LoaiDonTu
    {
        public string LoaiDonTuID { get; set; }
        public string TenLoaiDonTu { get; set; }
        public string ThoiHanGiaiQuyet { get; set; }
        public Nullable<bool> TrangThai { get; set; }
        public string MoTa { get; set; }
        public Nullable<byte> ThoiHanHuyDon { get; set; }
        public string Link { get; set; }
        public Nullable<System.DateTime> ThoiGianKichHoat { get; set; }
        public Nullable<System.DateTime> ThoiGianKetThuc { get; set; }
        public string HKXuLy { get; set; }
    }
}
