//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SupportStudentSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Lop
    {
        public string MaLop { get; set; }
        public string TenLop { get; set; }
        public string NienKhoaID { get; set; }
        public string MaHDT { get; set; }
        public string MaNganh { get; set; }
    }
}
