//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SupportStudentSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MonHoc
    {
        public string MaMH { get; set; }
        public string TenMH { get; set; }
        public Nullable<int> TongTC { get; set; }
        public Nullable<int> SoTC_LT { get; set; }
        public Nullable<int> SoTC_TH { get; set; }
        public Nullable<int> SoTC_DATT { get; set; }
        public Nullable<int> SoTC_DATN { get; set; }
        public string LoaiMonHocID { get; set; }
        public Nullable<int> DiemHe1 { get; set; }
        public Nullable<int> DiemHe2 { get; set; }
        public Nullable<int> DiemHe3 { get; set; }
        public string DonViQuanLy { get; set; }
    }
}
