//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SupportStudentSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhanQuyenXuLyDonTu
    {
        public string NhanVienID { get; set; }
        public string LoaiDonTuID { get; set; }
        public Nullable<bool> Xem { get; set; }
        public Nullable<bool> XuLy { get; set; }
    }
}
