//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SupportStudentSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhanQuyenChucNang
    {
        public string NhanVienID { get; set; }
        public string TenBangDuLieu { get; set; }
        public Nullable<bool> Xem { get; set; }
        public Nullable<bool> Sua { get; set; }
        public Nullable<bool> ThemMoi { get; set; }
    }
}
