//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SupportStudentSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhongHoc
    {
        public string PhongHocID { get; set; }
        public string CoSoHoc { get; set; }
        public Nullable<byte> SoLuongBan { get; set; }
        public string LoaiPhong { get; set; }
        public string KyHieu { get; set; }
        public string GhiChu { get; set; }
    }
}
