//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SupportStudentSystem.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class QUANLYSINHVIENEntities : DbContext
    {
        public QUANLYSINHVIENEntities()
            : base("name=QUANLYSINHVIENEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CT_Diem_HK> CT_Diem_HK { get; set; }
        public virtual DbSet<CT_HK> CT_HK { get; set; }
        public virtual DbSet<CT_LichThi> CT_LichThi { get; set; }
        public virtual DbSet<CT_PhieuHuyHocPhan> CT_PhieuHuyHocPhan { get; set; }
        public virtual DbSet<CT_PhieuRutHocPhan> CT_PhieuRutHocPhan { get; set; }
        public virtual DbSet<ChungChiTiengAnh> ChungChiTiengAnh { get; set; }
        public virtual DbSet<ChungChiTinHoc> ChungChiTinHoc { get; set; }
        public virtual DbSet<ChungChiTinHocNganHan> ChungChiTinHocNganHan { get; set; }
        public virtual DbSet<DiemQuyDoi> DiemQuyDoi { get; set; }
        public virtual DbSet<DonDeNghiXetTotNghiep> DonDeNghiXetTotNghiep { get; set; }
        public virtual DbSet<DonTu> DonTu { get; set; }
        public virtual DbSet<DonXinChuyenCaThi> DonXinChuyenCaThi { get; set; }
        public virtual DbSet<DonXinNhanDiemI_HoanThi> DonXinNhanDiemI_HoanThi { get; set; }
        public virtual DbSet<DonXinNhapHocLai> DonXinNhapHocLai { get; set; }
        public virtual DbSet<DonXinTamNghiHoc> DonXinTamNghiHoc { get; set; }
        public virtual DbSet<DonXinThiXoaDiemI> DonXinThiXoaDiemI { get; set; }
        public virtual DbSet<HeDaoTao> HeDaoTao { get; set; }
        public virtual DbSet<Khoa> Khoa { get; set; }
        public virtual DbSet<LichThi> LichThi { get; set; }
        public virtual DbSet<LoaiDonTu> LoaiDonTu { get; set; }
        public virtual DbSet<LoaiMonHoc> LoaiMonHoc { get; set; }
        public virtual DbSet<Lop> Lop { get; set; }
        public virtual DbSet<MonHoc> MonHoc { get; set; }
        public virtual DbSet<MonHocTuongDuong> MonHocTuongDuong { get; set; }
        public virtual DbSet<Nganh> Nganh { get; set; }
        public virtual DbSet<NhanVien> NhanVien { get; set; }
        public virtual DbSet<PhanHoi> PhanHoi { get; set; }
        public virtual DbSet<PhanQuyenChucNang> PhanQuyenChucNang { get; set; }
        public virtual DbSet<PhanQuyenXuLyDonTu> PhanQuyenXuLyDonTu { get; set; }
        public virtual DbSet<PhieuHuyHocPhanDaDangKy> PhieuHuyHocPhanDaDangKy { get; set; }
        public virtual DbSet<PhieuRutBotHocPhanDaDangKy> PhieuRutBotHocPhanDaDangKy { get; set; }
        public virtual DbSet<PhongHoc> PhongHoc { get; set; }
        public virtual DbSet<SinhVien> SinhVien { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<TinhTrang_GhiChu> TinhTrang_GhiChu { get; set; }
        public virtual DbSet<TinhTrangXuLy> TinhTrangXuLy { get; set; }
        public virtual DbSet<ThoiGianNhanDon> ThoiGianNhanDon { get; set; }
    }
}
