//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SupportStudentSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SinhVien
    {
        public string MSSV { get; set; }
        public string MaLop { get; set; }
        public string HoLot { get; set; }
        public string Ten { get; set; }
        public Nullable<bool> GioiTinh { get; set; }
        public Nullable<System.DateTime> NgaySinh { get; set; }
        public string NoiSinh { get; set; }
        public string DanToc { get; set; }
        public string TonGiao { get; set; }
        public string SDTSV { get; set; }
        public string DiaChi { get; set; }
        public string emailSV { get; set; }
        public string SDT_LienHe { get; set; }
        public string DiaChiThuongTru { get; set; }
        public string MatKhau { get; set; }
        public string CauHoiBaoMat { get; set; }
        public string TraLoiBaoMat { get; set; }
    }
}
