//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SupportStudentSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TinhTrangXuLy
    {
        public long STT { get; set; }
        public string DonTuID { get; set; }
        public string NhanVienID { get; set; }
        public string TinhTrang { get; set; }
        public Nullable<System.DateTime> NgayXuLy { get; set; }
        public string GhiChu { get; set; }
    }
}
